/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-container-lowest": "#ffffff",
        "error": "#ba1a1a",
        "on-background": "#191c1e",
        "on-tertiary-container": "#e17f5d",
        "on-primary-container": "#7a97e2",
        "on-primary": "#ffffff",
        "primary-fixed-dim": "#b1c5ff",
        "background": "#f7f9fb",
        "tertiary": "#3b0d00",
        "on-tertiary-fixed": "#390c00",
        "surface-variant": "#e0e3e5",
        "secondary": "#515f74",
        "inverse-primary": "#b1c5ff",
        "surface": "#f7f9fb",
        "primary-container": "#002d72",
        "on-surface": "#191c1e",
        "inverse-surface": "#2d3133",
        "secondary-fixed": "#d5e3fc",
        "primary": "#001a48",
        "on-error": "#ffffff",
        "tertiary-fixed": "#ffdbd0",
        "primary-fixed": "#dae2ff",
        "on-tertiary": "#ffffff",
        "on-surface-variant": "#444651",
        "surface-container": "#eceef0",
        "secondary-container": "#d5e3fc",
        "on-error-container": "#93000a",
        "outline-variant": "#c4c6d2",
        "on-tertiary-fixed-variant": "#7a3014",
        "surface-container-highest": "#e0e3e5",
        "outline": "#747782",
        "on-primary-fixed-variant": "#224489",
        "surface-container-low": "#f2f4f6",
        "secondary-fixed-dim": "#b9c7df",
        "on-secondary-fixed": "#0d1c2e",
        "tertiary-container": "#5d1b02",
        "surface-tint": "#3d5ca2",
        "on-secondary": "#ffffff",
        "inverse-on-surface": "#eff1f3",
        "on-secondary-fixed-variant": "#3a485b",
        "surface-dim": "#d8dadc",
        "error-container": "#ffdad6",
        "surface-bright": "#f7f9fb",
        "surface-container-high": "#e6e8ea",
        "tertiary-fixed-dim": "#ffb59c"
      },
      fontFamily: {
        "headline": ["Manrope"],
        "body": ["Inter"],
        "label": ["Inter"]
      },
      borderRadius: {"DEFAULT": "0.125rem", "lg": "0.25rem", "xl": "0.5rem", "full": "0.75rem"},
    },
  },
  plugins: [],
}
